---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes

- shell: sudo apt-get install git-core
- shell: wget http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-2.1.0-Linux-x86_64.sh
- shell: bash Anaconda-2.1.0-Linux-x86_64.sh